<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ATMECSINLT-085" ignored="0" name="Test validate CHROMEcom.atmecs.sample.testscripts.Home" tests="1" failures="1" timestamp="25 Oct 2019 13:17:19 GMT" time="16.392" errors="0">
  <testcase name="@AfterMethod tearDown" time="0.002" classname="com.atmecs.sample.extentreport.Extent">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.atmecs.sample.extentreport.Extent.tearDown(Extent.java:64)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="verifytable" time="3.724" classname="com.atmecs.sample.testscripts.Home">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 4, Size: 4">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.atmecs.sample.testscripts.Home.getCellData(Home.java:123)
at com.atmecs.sample.testscripts.Home.verifytable(Home.java:36)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifytable -->
</testsuite> <!-- Test validate CHROMEcom.atmecs.sample.testscripts.Home -->
